apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.7.*
      helm:
        releaseName: argocd
        valuesObject:
          global:
            domain: argocd.local.tylerc.me
          configs:
            cm:
              kustomize.buildOptions: --enable-helm
            params:
              # disable TLS termination as Cilium Gateway API will handle it
              server.insecure: true
          controller:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: "argocd"
                selector:
                  prometheus: argocd
          redis:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: "argocd"
                selector:
                  prometheus: argocd
          server:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: "argocd"
                selector:
                  prometheus: argocd
          repoServer:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                namespace: "argocd"
                selector:
                  prometheus: argocd
    - repoURL: https://github.com/supertylerc/sre-portfolio.git
      path: k8s-lab/argocd
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
