apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.*
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
          featureGates: ExperimentalGatewayAPISupport=true
          enableCertificateOwnerRef: true
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              prometheusInstance: cert-manager
    - repoURL: https://github.com/supertylerc/sre-portfolio.git
      path: k8s-lab/cert-manager
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
