apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 58.*
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          prometheus:
            prometheusSpec:    
              storageSpec: 
               volumeClaimTemplate:
                 spec:
                   storageClassName: longhorn
                   accessModes: ["ReadWriteOnce"]
                   resources:
                     requests:
                       storage: 2Gi
    - repoURL: https://github.com/supertylerc/sre-portfolio.git
      path: k8s-lab/kube-prometheus-stack
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
