apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 58.*
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          prometheus:
            prometheusSpec:    
              paused: false
              storageSpec: 
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 4Gi
              secrets: ['etcd-client-cert']
              thanos:
                objectStorageConfig:
                  existingSecret:
                    name: thanos-objstore
                    key: objstore.yml
              thanosService:
                enabled: true
              thanosServiceMonitor:
                enabled: true
          alertmanager:
            alertmanagerSpec:
              alertmanagerConfigMatcherStrategy:
                type: None
          defaultRules:
            rules:
              kubeProxy: false
          grafana:
            sidecar:
              datasources:
                defaultDatasourceEnabled: false
            deleteDatasources:
              - name: Prometheus
            additionalDataSources:
              - name: thanos
                type: prometheus
                url: "http://thanos-query-frontend:9090"
                uid: thanos
                isDefault: true
                jsonData:
                  prometheusType: "Thanos"
              - name: loki
                type: loki
                url: "http://loki-read:3100"
                uid: loki
                isDefault: false
          kubeEtcd:
            service:
              port: "2379"
              targetPort: "2379"
            serviceMonitor:
              scheme: https
              insecureSkipVerify: false
              serverName: localhost
              caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
              certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
              keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
    - repoURL: https://github.com/supertylerc/sre-portfolio.git
      path: k8s-lab/kube-prometheus-stack
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
