apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.*
      helm:
        releaseName: longhorn
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          metrics:
            serviceMonitor:
              enabled: true
    - repoURL: https://github.com/supertylerc/sre-portfolio.git
      path: k8s-lab/longhorn
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
