---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
data:
  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  REDIS_LEADER_KEY: {{ .Values.redis.leader_key | b64enc }}
  APP_ENV: {{ .Values.app_env | b64enc }}
  METRICS_PORT: {{ .Values.metricsPort | b64enc }}
