---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: scheduler
    app.kubernetes.io/name: scheduler
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
