---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: "10.0.42.52"
  listeners:
  - hostname: "*.local.tylerc.me"
    name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - hostname: "*.local.tylerc.me"
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
        - name: local-tylerc-me-wildcard
    allowedRoutes:
      namespaces:
        from: All
