apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: cert-manager-prometheus
  namespace: monitoring-system
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prometheus-stack-alertmanager
      namespace: monitoring-system
      pathPrefix: /
      port: http-web
  externalUrl: "http://cert-manager-prometheus.kube-system:9090"
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      prometheus: cert-manager
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      prometheus: cert-manager
  retention: 6h
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: cert-manager
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      prometheus: cert-manager
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: cert-manager
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: longhorn
  thanos:
    blockSize: 2h
    objectStorageConfig:
      key: objstore.yml
      name: thanos-objstore
