---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  hostnames:
  - grafana.local.tylerc.me
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gateway
    namespace: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: kube-prometheus-stack-grafana
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alert-manager
  namespace: monitoring-system
spec:
  hostnames:
  - alert-manager.local.tylerc.me
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cilium-gateway
    namespace: gateway
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: kube-prometheus-stack-alertmanager
      port: 9093
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
