name: scheduler-ci
on:
  push:
    paths:
      - scheduler/**
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: latest
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          args: --enable-all

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
          working-directory: ./scheduler
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scheduler
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: build
        run: make build
  test-coverage:
    name: Go test coverage, scheduler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scheduler
    steps:
      - uses: actions/checkout@v4
      - name: Go test coverage
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: ./scheduler/cover.out
          base-path: ./scheduler
