name: Validate packer template file in a directory

on:
  pull_request:
    paths:
      - packer/**
env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `packer init`
        id: init
        run: "packer init ./packer"
      - name: Run `packer validate`
        id: validate
        run: "packer validate -var 'api_token=xyz' ./packer"
